POST http://localhost:8050/products
Content-Type: application/json

{
	"code": "p1",
	"price": "10"
}

###

GET http://localhost:8050/products

###
PUT http://localhost:8050/products/1
Content-Type: application/json

{
	"code": "p1",
	"price": "100"
}

###

DELETE http://localhost:8050/products/1