// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gorm.io/gorm"
	"lpfigueiredo/go-crud/product"
)

// Injectors from wire.go:

func initProductAPI(db *gorm.DB) product.ProductAPI {
	productRepository := product.ProductRepository{
		DB: db,
	}
	productService := product.ProductService{
		ProductRepository: productRepository,
	}
	productAPI := product.ProductAPI{
		ProductService: productService,
	}
	return productAPI
}
